export const GET_WEATHER_FULFILLED = 'GET_WEATHER_FULFILLED';
export const GET_CITY_WEATHER_FULFILLED = 'GET_CITY_WEATHER_FULFILLED';
export const GET_WEATHER_FAILED = 'GET_WEATHER_FAILED';
export const AUTO_FETCHING_WEATHER = 'AUTO_FETCHING_WEATHER';
export const CITY_FETCHING_WEATHER = 'CITY_FETCHING_WEATHER';